### ISSUE TITLE
L2T v6 / API V2 - Meta information - Wrong JSON Property Names: PreviousToken, NextToken?

### ISSUE THREAD

**Issue by JeepNL** [JoeMayo/LinqToTwitter#300]
# General Issue

### Please let us know what you use:

1. .NET SDK version:  7 preview 4                             
2. LINQ To Twitter Version:  6.14                  
3. Twitter API version (v1/v2) 👇
    - [ ] Twitter API v1                              
    - [x] Twitter API v2                          
      
      - v2 access level 👇
        - [ ] Essential access 
        - [x] Elevated access 
        - [ ] Academic research access
      - Type of v2 App 👇
        - [x] Public Client  (Native App / Single Page App)
        - [ ] Confidential Client (Web App / Automated App or Bot)

### Describe the issue

The Twiter API v2 JSON response of a `TweetType.TweetsTimeline` contains something like this:

```
  "meta": {
    "result_count": 2,
    "newest_id": "1529380845185900544",
    "oldest_id": "1529378452150923266"
  }
```

But when I try to retrieve this info with L2T like this

        int resultCount = tweetQuery?.Meta?.ResultCount ?? 0;
        string newestTweetId = tweetQuery?.Meta?.NextToken ?? "0";
        string oldestTweetId = tweetQuery?.Meta?.PreviousToken ?? "0";

`tweetQuery?.Meta?.NextToken` & `tweetQuery?.Meta?.PreviousToken` are always 0

`tweetQuery?.Meta?.ResultCount` gives the correct value

I think the JSON Property Names in [TweetMeta.cs](https://github.com/JoeMayo/LinqToTwitter/blob/177092830f2c96e64d12c49c97e8e282165c9c61/src/LinqToTwitter6/LinqToTwitter/Tweet/TweetMeta.cs) & possibly (_haven't tested that_) [ListMeta.cs](https://github.com/JoeMayo/LinqToTwitter/blob/177092830f2c96e64d12c49c97e8e282165c9c61/src/LinqToTwitter6/LinqToTwitter/List/ListMeta.cs) / [ListRequestProcessorTests.cs](https://github.com/JoeMayo/LinqToTwitter/blob/177092830f2c96e64d12c49c97e8e282165c9c61/src/LinqToTwitter6/LinqToTwitter.Tests/ListTests/ListRequestProcessorTests.cs) need to be changed to `newest_id` & `oldest_id`

**Comment by JoeMayo** [comment]
The `NextToken` and `PreviousToken` are still good for Tweet Timelines. The `newest_id` and `oldest_id` are new properties.

**Comment by JeepNL** [comment]
Ah, ok, I missed that.
